### ISSUE TITLE
Millorar Model E-R 

### ISSUE THREAD

**Issue by Barto24** [JoseProgramador1/Projecte-2-Tapping#37]
Afegir la taula pais, ciutat, cp, chat i linieaDeChat
 Revisar la part de tapa, categoria i local

**Comment by Julss799** [comment]
Hem decidit que continuarem amb l'idea inicial, però definint la categoria molt bé per evitar confusions.
![TerceraVersioFinal](https://user-images.githubusercontent.com/113366844/218499285-15f90ae6-5498-494c-b4f7-51f49cb9b23b.png)
