### ISSUE TITLE
Menú de l'aplicació Android

### ISSUE THREAD

**Issue by joan024** [JoseProgramador1/Projecte-2-Tapping#51]

**Comment by Barto24** [comment]
package com.example.tappingandroid;

import android.content.Intent;
import android.os.Bundle;
import android.view.ContextMenu;
import android.view.MenuInflater;
import android.view.MenuItem;
import android.view.View;
import android.widget.AdapterView;

import androidx.annotation.NonNull;
import androidx.annotation.StringRes;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.view.GravityCompat;
import androidx.drawerlayout.widget.DrawerLayout;

import com.google.android.material.navigation.NavigationView;

import GestioDeRegistres.IniciSessio;
import GestioDeRegistres.Registre;

public class Menu extends AppCompatActivity  {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_inici);
    }


    @Override
    public boolean onCreateOptionsMenu(android.view.Menu menu) {
        MenuInflater inflater = getMenuInflater();
        inflater.inflate(R.menu.menu_navigation, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        Intent intent;
        switch (item.getItemId()) {
            case R.id.btn_dades:
                intent = new Intent(this, IniciSessio.class);
                startActivity(intent);
                return true;

            case R.id.btn_login:
                intent = new Intent(this, Registre.class);
                startActivity(intent);
                return true;
            default:
                return super.onOptionsItemSelected(item);
        }
    }

}
